"""Criacao inicial de todas as tabelas

Revision ID: 8ce5333b3c7a
Revises: 
Create Date: 2026-06-24 15:01:50.606396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce5333b3c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pontuacao_socioeconomica', sa.Float(), nullable=True),
    sa.Column('respostas', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_candidatos_id'), 'candidatos', ['id'], unique=False)
    op.create_table('questionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionarios_id'), 'questionarios', ['id'], unique=False)
    op.create_index(op.f('ix_questionarios_nome'), 'questionarios', ['nome'], unique=True)
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cartao_id')
    )
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('texto_pergunta', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questoes_id'), 'questoes', ['id'], unique=False)
    op.create_table('alternativas_pesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('texto_alternativa', sa.String(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternativas_pesos_id'), 'alternativas_pesos', ['id'], unique=False)
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('sessao_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_id'), 'registros', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_id'), table_name='registros')
    op.drop_table('registros')
    op.drop_index(op.f('ix_alternativas_pesos_id'), table_name='alternativas_pesos')
    op.drop_table('alternativas_pesos')
    op.drop_index(op.f('ix_questoes_id'), table_name='questoes')
    op.drop_table('questoes')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_table('alunos')
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_questionarios_nome'), table_name='questionarios')
    op.drop_index(op.f('ix_questionarios_id'), table_name='questionarios')
    op.drop_table('questionarios')
    op.drop_index(op.f('ix_candidatos_id'), table_name='candidatos')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
